// <auto-generated />
using System;
using ChessApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChessApp.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260131221845_AddedModels")]
    partial class AddedModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChessApp.API.Models.Opening", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Color")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("RootNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RootNodeId");

                    b.HasIndex("UserId", "Color", "Name")
                        .IsUnique();

                    b.ToTable("Openings", (string)null);
                });

            modelBuilder.Entity("ChessApp.API.Models.OpeningNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Fen")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("LineType")
                        .HasColumnType("integer");

                    b.Property<string>("MoveSan")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("OpeningId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentNodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentNodeId");

                    b.HasIndex("OpeningId", "Fen")
                        .IsUnique();

                    b.HasIndex("OpeningId", "ParentNodeId");

                    b.ToTable("OpeningNodes", (string)null);
                });

            modelBuilder.Entity("ChessApp.API.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Revoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("ChessApp.API.Models.RepertoireItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Color")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("OpeningId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OpeningId");

                    b.HasIndex("ParentId");

                    b.HasIndex("UserId", "OpeningId");

                    b.HasIndex("UserId", "ParentId", "Name")
                        .IsUnique();

                    b.HasIndex("UserId", "Color", "ParentId", "SortOrder");

                    b.ToTable("RepertoireItems", (string)null);
                });

            modelBuilder.Entity("ChessApp.API.Models.TrainingNodeStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("FailedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("LastTrainedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextDueAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OpeningNodeId")
                        .HasColumnType("uuid");

                    b.Property<int>("TrainedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OpeningNodeId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "OpeningNodeId")
                        .IsUnique();

                    b.ToTable("TrainingNodeStats", (string)null);
                });

            modelBuilder.Entity("ChessApp.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("FailedLoginCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("GoogleSubject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("LockoutUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ChessApp.API.Models.Opening", b =>
                {
                    b.HasOne("ChessApp.API.Models.OpeningNode", "RootNode")
                        .WithMany()
                        .HasForeignKey("RootNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RootNode");
                });

            modelBuilder.Entity("ChessApp.API.Models.OpeningNode", b =>
                {
                    b.HasOne("ChessApp.API.Models.Opening", "Opening")
                        .WithMany()
                        .HasForeignKey("OpeningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChessApp.API.Models.OpeningNode", "ParentNode")
                        .WithMany("Children")
                        .HasForeignKey("ParentNodeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Opening");

                    b.Navigation("ParentNode");
                });

            modelBuilder.Entity("ChessApp.API.Models.RefreshToken", b =>
                {
                    b.HasOne("ChessApp.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChessApp.API.Models.RepertoireItem", b =>
                {
                    b.HasOne("ChessApp.API.Models.Opening", "Opening")
                        .WithMany()
                        .HasForeignKey("OpeningId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ChessApp.API.Models.RepertoireItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Opening");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ChessApp.API.Models.TrainingNodeStats", b =>
                {
                    b.HasOne("ChessApp.API.Models.OpeningNode", "OpeningNode")
                        .WithMany()
                        .HasForeignKey("OpeningNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OpeningNode");
                });

            modelBuilder.Entity("ChessApp.API.Models.OpeningNode", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("ChessApp.API.Models.RepertoireItem", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
